### ISSUE TITLE
操作改善提案

### ISSUE THREAD

**Issue by kogepan159** [MaitoMisao/Tabata#1]
・ロングタップでリセットは気づきにくいです。。。リセットボタンを別に用意してほうがいいですmm
・リセットボタンの「キャンセル」を押された時は何をしようとしていたんでしょうか？

**Comment by MaitoMisao** [comment]
ありがとうございます！リセットボタン改善してみます。。。
キャンセルは押した後、そのまま元に戻る（タイマーが再開する）処理を書こうと思ってました。

**Comment by kogepan159** [comment]
了解です！
そこの部分を削除してしまったので、戻しておきましたmm
